var mapper = require('./delivery-ticket-mapper');

var ticket = {
    "accountNumber": 161040,
    "custPO": "123456",
    "contractNo": "4289392",
    "address1": "Deliveries Within a Reasonable Distance",
    "address2": "of our Bow plant",
    "address3": "",
    "address4": "LE67 1TL",
    "uom": "M3",
    "splitLoad": "",
    "loadTicketLoad": "42822158",
    "actualLeaveWBDate": "2016-09-12T23:00:00.000Z",
    "actualLeaveWBTime": 2300,
    "ticketNumber": "71809310",
    "exWorks": "N",
    "haulierName": "RAYMOND  HODGSON",
    "haulier": 1424008,
    "retroTicket": "N",
    "brand": "LC",
    "plantName": "Bow  RMX Prodn",
    "readyMixDescription": "C16/20 20mm CEM I . S2 . .",
    "itemDescription2": "Readymix",
    "ceMarking": "N",
    "vatRegNo": "",
    "despatchedBy": "SQATest2",
    "cashSaleLine": "0",
    "cashSaleTotalGoods": "0",
    "cashSaleVATPercent": "0",
    "cashSaleAmountPayable": "0",
    "orderNo": 22154597,
    "loadLineStatus": "500",
    "lineBU": "2952040",
    "itemNumber": "RMX ENC",
    "itemDescription": "Design & Designated",
    "customerName": "HARRIS PM LTD",
    "siteLocation": "Bow",
    "loadLineQuantity": "6.00",
    "plannedOnsiteTime": 1,
    "vehicleReg": "LM58 ZVD",
    "works": "BWL",
    "orderLineQuantity": "6.00",
    "siteContact": "P M Harris Ltd",
    "contactTelephoneNumber": "01335331910",
    "plannedLoadTicketTime": 2346,
    "actLoadTicketTime": 2255,
    "driverName": "RAYMOND HODGSON",
    "estimatedOnSiteTime": 2315,
    "estimatedOnSiteDate": "2016-09-12T23:00:00.000Z",
    "estimatedLeaveWBTime": 2305,
    "deliveredQty": "6.00",
    "OSQuantity": "0",
    "loadingQuantity": "0",
    "deliveryInstructions": "",
    "unifiedDescription": "C16/20 20mm CEM I . S2 . .",
    "plannedOnSiteDateTime": "2016-09-13T00:01:00",
    "estimatedOnSiteDateTime": "2016-09-13T23:15:00",
    "actualLeaveWBDateTime": "2016-09-13T23:00:00",
    "pushed": true
};

var user = {
  "id" : "rJeXyfdrH",
  "username" : "daisy",
  "name" : "Daisy Dialer",
  "position" : "DRIVER",
  "phone" : "(265) 754 8176",
  "email" : "daisy@wfm.com",
  "notes" : "Trever doesn't work during the weekends.",
  "avatar" : "https://s3.amazonaws.com/uifaces/faces/twitter/madysondesigns/128.jpg",
  "vehicle" : "LM58 ZVD",
  "password": "MD5",
  "works": "TOL"
};

var workorder = mapper.map(ticket, user);
console.log('ticket', ticket, 'workorder', JSON.stringify(workorder));
